name: ✨

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  main:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout lastest code
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn
      - run: yarn format:check
